[package]
name = "rs-moddotplot"
version = "0.1.0"
edition = "2021"
authors = ["Keisuke K. Oshima <koisland@pm.me>"]
description = "Rust port of ModDotPlot"
repository = "https://github.com/logsdon-lab/rs-moddotplot"
readme = "README.md"
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]
murmur3 = "0.5.2"
indexmap = "2.9.0"
noodles = { version = "0.96.0", features = ["fasta"] }
rayon = "1.10.0"
plotters = { version = "0.3.7", optional = true}
itertools = { version = "0.14.0", optional = true}
ordered-float = {version = "5.1.0", optional = true}

[dev-dependencies]
flate2 = "1.1.5"

[features]
default = []
plot = ["dep:plotters", "dep:itertools", "dep:ordered-float"]

[[example]]
name = "ident"
path = "examples/ident.rs"

[[example]]
name = "local_ident"
path = "examples/local_ident.rs"

[[example]]
name = "group_ident"
path = "examples/group_ident.rs"

[[example]]
name = "plot_self_ident"
path = "examples/plot_self_ident.rs"
